=encoding utf8


=head1 PomBase-Chobo

Code for reading OBO files into a Chado database using PostgreSQL COPY.


=head2 Installation

To install, run the following commands:

    perl Build.PL
    ./Build installdeps
    ./Build test
    ./Build install


=head2 Example usage

C<chobo_load 'dbi:Pg:dbname=test-db' my_username my_password *.obo>


=head2 License and Copyright

Copyright (C) 2016 Kim Rutherford

This program is free software; you can redistribute it and/or modify it
under the terms of either: the GNU General Public License as published
by the Free Software Foundation; or the Artistic License.

See http://dev.perl.org/licenses/ for more information.
